<?xml version="1.0" encoding="utf-8"?><Database Name="Zaya" Class="ZayaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SFB5OFQ;Initial Catalog=Zaya;User ID=sa" SettingsObjectName="Zaya.Properties.Settings" SettingsPropertyName="ZayaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Commentaire" Member="Commentaire">
    <Type Name="Commentaire">
      <Column Name="idCommentaire" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idQuiz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idLecon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="textCommentaire" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="dateCommentaire" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idUtilisateur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lecon_Commentaire" Member="Lecon" ThisKey="idLecon" OtherKey="idLecon" Type="Lecon" IsForeignKey="true" />
      <Association Name="Quiz_Commentaire" Member="Quiz" ThisKey="idQuiz" OtherKey="idQuiz" Type="Quiz" IsForeignKey="true" />
      <Association Name="Utilisateur_Commentaire" Member="Utilisateur" ThisKey="idUtilisateur" OtherKey="idUtilisateur" Type="Utilisateur" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lecon" Member="Lecon">
    <Type Name="Lecon">
      <Column Name="idLecon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="idUtilisateur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textLecon" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="idMatiere" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateAjoute" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Lecon_Commentaire" Member="Commentaire" ThisKey="idLecon" OtherKey="idLecon" Type="Commentaire" />
      <Association Name="Lecon_Question" Member="Question" ThisKey="idLecon" OtherKey="idLecon" Type="Question" />
      <Association Name="Matiere_Lecon" Member="Matiere" ThisKey="idMatiere" OtherKey="idMatiere" Type="Matiere" IsForeignKey="true" />
      <Association Name="Utilisateur_Lecon" Member="Utilisateur" ThisKey="idUtilisateur" OtherKey="idUtilisateur" Type="Utilisateur" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Matiere" Member="Matiere">
    <Type Name="Matiere">
      <Column Name="idMatiere" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Matiere_Lecon" Member="Lecon" ThisKey="idMatiere" OtherKey="idMatiere" Type="Lecon" />
      <Association Name="Matiere_Quiz" Member="Quiz" ThisKey="idMatiere" OtherKey="idMatiere" Type="Quiz" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Question">
    <Type Name="Question">
      <Column Name="idQuestion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idLecon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textQuestion" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="idTypeQuestion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Question_Reponse" Member="Reponse" ThisKey="idQuestion" OtherKey="idQuestion" Type="Reponse" />
      <Association Name="Question_ResultatQuiz" Member="ResultatQuiz" ThisKey="idQuestion" OtherKey="idQuestion" Type="ResultatQuiz" />
      <Association Name="Lecon_Question" Member="Lecon" ThisKey="idLecon" OtherKey="idLecon" Type="Lecon" IsForeignKey="true" />
      <Association Name="TypeQuestion_Question" Member="TypeQuestion" ThisKey="idTypeQuestion" OtherKey="idTypeQuestion" Type="TypeQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quiz" Member="Quiz">
    <Type Name="Quiz">
      <Column Name="idQuiz" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="duree" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="tempsEstime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="idMatiere" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUtilisateur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateQuiz" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Quiz_Commentaire" Member="Commentaire" ThisKey="idQuiz" OtherKey="idQuiz" Type="Commentaire" />
      <Association Name="Quiz_ResultatQuiz" Member="ResultatQuiz" ThisKey="idQuiz" OtherKey="idQuiz" Type="ResultatQuiz" />
      <Association Name="Matiere_Quiz" Member="Matiere" ThisKey="idMatiere" OtherKey="idMatiere" Type="Matiere" IsForeignKey="true" />
      <Association Name="Utilisateur_Quiz" Member="Utilisateur" ThisKey="idUtilisateur" OtherKey="idUtilisateur" Type="Utilisateur" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reponse" Member="Reponse">
    <Type Name="Reponse">
      <Column Name="idReponse" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idQuestion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valider" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="txtReponse" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Reponse_ReponseQuiz" Member="ReponseQuiz" ThisKey="idReponse" OtherKey="idReponse" Type="ReponseQuiz" />
      <Association Name="Question_Reponse" Member="Question" ThisKey="idQuestion" OtherKey="idQuestion" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReponseQuiz" Member="ReponseQuiz">
    <Type Name="ReponseQuiz">
      <Column Name="idReponseQuiz" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idResultatQuiz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idReponse" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="textReponse" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Reponse_ReponseQuiz" Member="Reponse" ThisKey="idReponse" OtherKey="idReponse" Type="Reponse" IsForeignKey="true" />
      <Association Name="ResultatQuiz_ReponseQuiz" Member="ResultatQuiz" ThisKey="idResultatQuiz" OtherKey="idResultatQuiz" Type="ResultatQuiz" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResultatQuiz" Member="ResultatQuiz">
    <Type Name="ResultatQuiz">
      <Column Name="idResultatQuiz" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idQuiz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idQuestion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ResultatQuiz_ReponseQuiz" Member="ReponseQuiz" ThisKey="idResultatQuiz" OtherKey="idResultatQuiz" Type="ReponseQuiz" />
      <Association Name="Question_ResultatQuiz" Member="Question" ThisKey="idQuestion" OtherKey="idQuestion" Type="Question" IsForeignKey="true" />
      <Association Name="Quiz_ResultatQuiz" Member="Quiz" ThisKey="idQuiz" OtherKey="idQuiz" Type="Quiz" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TypeQuestion" Member="TypeQuestion">
    <Type Name="TypeQuestion">
      <Column Name="idTypeQuestion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TypeQuestion_Question" Member="Question" ThisKey="idTypeQuestion" OtherKey="idTypeQuestion" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.TypeUtilisateur" Member="TypeUtilisateur">
    <Type Name="TypeUtilisateur">
      <Column Name="idTypeUtilisateur" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="TypeUtilisateur_Utilisateur" Member="Utilisateur" ThisKey="idTypeUtilisateur" OtherKey="idTypeUtilisateur" Type="Utilisateur" />
    </Type>
  </Table>
  <Table Name="dbo.Utilisateur" Member="Utilisateur">
    <Type Name="Utilisateur">
      <Column Name="idUtilisateur" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="sexe" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pwd" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="dateInscription" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idTypeUtilisateur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Utilisateur_Commentaire" Member="Commentaire" ThisKey="idUtilisateur" OtherKey="idUtilisateur" Type="Commentaire" />
      <Association Name="Utilisateur_Lecon" Member="Lecon" ThisKey="idUtilisateur" OtherKey="idUtilisateur" Type="Lecon" />
      <Association Name="Utilisateur_Quiz" Member="Quiz" ThisKey="idUtilisateur" OtherKey="idUtilisateur" Type="Quiz" />
      <Association Name="TypeUtilisateur_Utilisateur" Member="TypeUtilisateur" ThisKey="idTypeUtilisateur" OtherKey="idTypeUtilisateur" Type="TypeUtilisateur" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.encrypt" Method="encrypt" IsComposable="true">
    <Parameter Name="pwd" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Data.Linq.Binary" />
  </Function>
</Database>